feat: sentry 설정
depromeet/13th-3team-client pull request #18
Opened 2023-04-22 08:16 UTC by oyeon-kwon

## 🤔 해결하려는 문제가 무엇인가요?
- sentry로 에러 노티 연결

## 🎉 변경 사항
- sentry로 에러 노티 연결

### 🙏 여기는 꼭 봐주세요!

### 사용 방법
- [sentry 홈페이지](https://depromeet-p2.sentry.io/issues/?referrer=onboarding-welcome-skip) (삼일무 구글 계정으로 가입 -> 계정 정보는 여기서 [슬랙 링크](https://depromeet13th.slack.com/archives/C0515QKKPPF/p1681829233415859))
<img width="1341" alt="스크린샷 2023-04-22 오후 5 16 00" src="https://user-images.githubusercontent.com/61301574/233772087-a5386ebe-b059-4548-98ee-428357e91608.png">

- 슬랙 노티
<img width="601" alt="스크린샷 2023-04-22 오후 5 13 24" src="https://user-images.githubusercontent.com/61301574/233771962-cf0f661d-77e8-4229-a18a-ccda17d80631.png">

## 🌄 스크린샷

## 📚 참고
- https://www.npmjs.com/package/@sentry/nextjs

2023-04-22 08:19 UTC, sjoleee requested changes

2023-04-22 08:19 UTC, sjoleee commented on .env
env 올라왔어유

2023-04-22 08:22 UTC, hyesungoh commented
오잉 왜 `ci` 안돌아가징

2023-04-23 14:51 UTC, oyeon-kwon commented on .env
아고! 지웠습니당

2023-04-23 15:13 UTC, sjoleee approved these changes

2023-04-25 09:18 UTC, hyesungoh approved these changes
👍 👍 👍 고생하셨어요!!

컨플릭트 나는 것만 리솔브해주시면 될 거 같습니다 ~~! 👍 

> 머지 이후 빌드되는 지만 확인 부탁드려요!!

2023-04-25 09:18 UTC, hyesungoh commented on next.config.js
> +};
👍 👍

2023-04-25 09:18 UTC, hyesungoh commented on next.config.js
> +    esmExternals: true,
요 부분은 왜 추가하신 것일까요 ?? 궁금해서 여쭤봅니다 !!

2023-04-25 10:41 UTC, oyeon-kwon commented on next.config.js
> +    esmExternals: true,
아 이거 import 안되면 이거 넣어야한다고 봐서 넣었던 것 같은데 지워도 될것같슴다 ㅎㅎ

2023-04-25 13:59 UTC, merged